# Generated by Django 2.0.7 on 2018-08-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qyulzung', '0002_auto_20180807_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='qz',
            name='ongoing',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
