# Generated by Django 2.0.7 on 2018-08-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qyulzung', '0003_qz_ongoing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternative',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='qz',
            name='cr1',
        ),
        migrations.RemoveField(
            model_name='qz',
            name='cr2',
        ),
        migrations.RemoveField(
            model_name='qz',
            name='cr3',
        ),
        migrations.AddField(
            model_name='alternative',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qz',
            name='alt',
            field=models.ManyToManyField(blank=True, related_name='alternative', to='qyulzung.Alternative'),
        ),
    ]
