# Generated by Django 2.0.7 on 2018-08-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qyulzung', '0004_auto_20180807_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternative',
            name='score',
        ),
        migrations.RemoveField(
            model_name='qz',
            name='alt',
        ),
        migrations.AddField(
            model_name='alternative',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='qyulzung.QZ'),
        ),
        migrations.AddField(
            model_name='qz',
            name='alt1',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='qz',
            name='alt2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='qz',
            name='alt3',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
