# Generated by Django 2.0.7 on 2018-08-07 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qyulzung', '0006_auto_20180807_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='alt',
        ),
        migrations.AddField(
            model_name='criteria',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='qyulzung.QZ'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
