# Generated by Django 2.0.7 on 2018-08-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qyulzung', '0007_auto_20180807_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='qz',
            name='alt1sco',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qz',
            name='alt2sco',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qz',
            name='alt3sco',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qz',
            name='cr1sco',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qz',
            name='cr2sco',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qz',
            name='cr3sco',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
