# Generated by Django 2.0.7 on 2018-08-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qyulzung', '0009_qz_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='qz',
            name='post_yn',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
